# Shared dev infra seed. Lives at infra/dev/ — same level as the prod
# `infra/tofu/` root, because the dev stack (Postgres + LocalStack +
# Zitadel) is transversal to every product, just like the prod stack is.
#
# Runs against the docker-compose Zitadel on `localhost:8080`
# (`infra/dev/docker-compose.yml::services.zitadel`), authenticated with
# the menu-sa PAT FirstInstance writes to `infra/dev/.zitadel-bootstrap/menu-sa.pat`.
#
# This root is the dev mirror of `infra/tofu/containers.tf::docker_container.menu_web`'s
# env block — every key the prod container gets is generated here too, so
# `products/menu/.env.local` in dev has the exact shape of prod's runtime
# env. No mind-shift between dev and prod: same keys, same source-of-truth
# (declarative), different backend (a local file vs an injected
# container env).
#
# Local-only state (`terraform.tfstate`, plaintext, gitignored) — fresh
# clone runs the whole seed in ~5 s, no encryption ceremony needed.
#
# Add a new product that needs OIDC: declare its zitadel_application_oidc
# next to `zitadel_application_oidc.menu` below, and emit a local_file
# under products/<name>/.env.local with the right env shape. Same compose
# stack serves all of them.

terraform {
  required_version = "~> 1.15"
  required_providers {
    zitadel = {
      source  = "zitadel/zitadel"
      version = "~> 2.12"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

provider "zitadel" {
  domain       = "localhost"
  port         = "8080"
  insecure     = true
  access_token = var.zitadel_pat
}

variable "zitadel_pat" {
  description = "Personal access token for the menu-sa machine user. Read from infra/dev/.zitadel-bootstrap/menu-sa.pat by products/menu/scripts/dev.go."
  type        = string
  sensitive   = true

  validation {
    condition     = length(var.zitadel_pat) > 0
    error_message = "zitadel_pat must be non-empty. Run docker compose up first."
  }
}

# ── Import the FirstInstance-created iedora org ──────────────────────────────

data "zitadel_orgs" "iedora" {
  name        = "iedora"
  name_method = "TEXT_QUERY_METHOD_EQUALS"
}

import {
  to = zitadel_org.iedora
  id = tolist(data.zitadel_orgs.iedora.ids)[0]
}

resource "zitadel_org" "iedora" {
  name       = "iedora"
  is_default = true
}

resource "zitadel_project" "iedora" {
  name                   = "iedora"
  org_id                 = zitadel_org.iedora.id
  project_role_assertion = true
}

# ── Menu OIDC app ────────────────────────────────────────────────────────────
# Same shape as prod (infra/tofu/zitadel.tf), two dev-only deltas:
#   - `dev_mode = true` so the auth endpoint accepts http:// redirect URIs
#   - `redirect_uris` points at localhost:3000

resource "zitadel_application_oidc" "menu" {
  org_id     = zitadel_org.iedora.id
  project_id = zitadel_project.iedora.id
  name       = "menu"

  redirect_uris             = ["http://localhost:3000/api/auth/callback"]
  post_logout_redirect_uris = ["http://localhost:3000/"]
  response_types            = ["OIDC_RESPONSE_TYPE_CODE"]
  grant_types               = ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE", "OIDC_GRANT_TYPE_REFRESH_TOKEN"]
  app_type                  = "OIDC_APP_TYPE_WEB"
  auth_method_type          = "OIDC_AUTH_METHOD_TYPE_BASIC"
  version                   = "OIDC_VERSION_1_0"
  access_token_type         = "OIDC_TOKEN_TYPE_JWT"
  dev_mode                  = true

  access_token_role_assertion = true
  id_token_role_assertion     = true
  id_token_userinfo_assertion = true

  login_version {
    login_v2 {
      base_uri = "http://localhost:3001/ui/v2/login"
    }
  }
}

# ── Menu session-cookie key — random per dev install ─────────────────────────
# Mirrors `random_password.menu_session_secret` in `infra/tofu/zitadel.tf`.
# Throwaway local state; tainting it (delete `.terraform/`) generates a
# fresh secret on the next `bun run dev`.

resource "random_password" "menu_session_secret" {
  length  = 48
  special = false
}

# ── Emit `.env.local` — the single source of truth for dev runtime env ──────
# Mirrors `infra/tofu/containers.tf::docker_container.menu_web.env` 1:1.
# Same keys, same shape, populated from the same kind of source
# (declarative). The only deltas:
#   - DATABASE_URL / S3_* / OTLP_ENDPOINT point at compose services
#   - ZITADEL_ISSUER_URL is http://localhost:8080
#   - OTEL exports are off by default (no collector running locally)
#
# Next loads this file second-highest-priority (after `.env.development.local`,
# which is NOT used here intentionally — we want one file, not two).

resource "local_file" "env" {
  # infra/dev/tofu/main.tf → ../../../products/menu/.env.local
  filename = "${path.module}/../../../products/menu/.env.local"
  content  = <<-EOT
    # AUTO-GENERATED by infra/dev/tofu/main.tf.
    # Regenerated by every `bun run dev`. Do not edit by hand — your
    # changes will be overwritten on the next seed run.
    #
    # Same keys as `infra/tofu/containers.tf::docker_container.menu_web.env`
    # so the dev runtime env matches prod 1:1.

    NODE_ENV=development

    # Database — compose service `postgres` on host port 5432.
    DATABASE_URL=postgresql://postgres:postgres@localhost:5432/menu

    # Auth — Zitadel docker-compose stack + this TF seed.
    MENU_PUBLIC_URL=http://localhost:3000
    MENU_SESSION_SECRET=${random_password.menu_session_secret.result}
    ZITADEL_ISSUER_URL=http://localhost:8080
    ZITADEL_OAUTH_CLIENT_ID=${zitadel_application_oidc.menu.client_id}
    ZITADEL_OAUTH_CLIENT_SECRET=${zitadel_application_oidc.menu.client_secret}
    ZITADEL_MANAGEMENT_TOKEN=${var.zitadel_pat}

    # Object storage — compose service `localstack`.
    S3_ENDPOINT=http://localhost:4566
    S3_REGION=us-east-1
    S3_ACCESS_KEY=test
    S3_SECRET_KEY=test
    S3_BUCKET=menu

    # Observability — local OpenObserve compose service. Spans + metrics
    # ship to it via OTLP HTTP, surfaced at http://localhost:5080.
    # Login: dev@iedora.local / dev-password (matches the compose env).
    OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:5080/api/default
    OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic%20${base64encode("dev@iedora.local:dev-password")}
    GIT_SHA=
    HOST_NAME=
  EOT

  # Owner-only — file holds the OIDC client_secret + session key.
  file_permission = "0600"
}
