package main

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// ── .env writer + composer ──────────────────────────────────────────────────

func writeEnvFile(path, body string) {
	if body == "" {
		return
	}
	header := "# AUTO-GENERATED by `task dev` (infra/cmd/dev).\n" +
		"# Composed from Tofu outputs + bin/zitadel-apply outputs.json + static\n" +
		"# literals + minted random secrets. The dynamic keys (session secret +\n" +
		"# Zitadel client_id/secret/PAT/signing keys) are stable across runs as\n" +
		"# long as outputs.json is preserved.\n" +
		"# Local-only values — no prod leak. Overrides live in `.env.local`.\n\n"
	if err := os.WriteFile(path, []byte(header+body+"\n"), envFileMode); err != nil {
		fail("write %s: %v", path, err)
	}
}

// composeMenuEnv produces the canonical menu env map for dev, composed
// from four sources:
//
//   - Static literals (NODE_ENV, S3_ACCESS_KEY=test for LocalStack, etc.)
//   - `tofu output -raw <name>` from infra/dev/tofu/ (DB url, OTEL endpoint, …)
//   - The bin/zitadel-apply outputs.json file (APP_ZITADEL_*)
//   - A randomly-minted MENU_SESSION_SECRET, persisted alongside the
//     zitadel-apply outputs so it survives `task dev` re-runs.
//
// menuOnHost determines whether DB / OTEL / S3 URLs point at the host
// (localhost:<port>) or at the docker network alias (infra-<svc>).
// `bun run dev` style work uses host; future containerized menu would
// flip to false.
func composeMenuEnv(devTofuDir, outputsJSONPath string, menuOnHost bool) map[string]string {
	out := map[string]string{
		// Static literals.
		"NODE_ENV":                "development",
		"NEXT_TELEMETRY_DISABLED": "1",
		"S3_REGION":               "us-east-1",
		"S3_ACCESS_KEY":           "test",
		"S3_SECRET_KEY":           "test",
		"S3_BUCKET":               "iedora-assets",
		"IEDORA_ADMIN_EMAILS":     "dev@iedora.local",
		"HOST_NAME":               "localhost",
		"GIT_SHA":                 "dev",
	}

	// Tofu outputs. Pair container/host variants by menuOnHost.
	tofuOut := func(name string) string {
		return captureIn(devTofuDir, "tofu", "output", "-raw", name)
	}
	out["MENU_PUBLIC_URL"] = tofuOut("menu_public_url")
	out["ZITADEL_ISSUER_URL"] = tofuOut("zitadel_issuer_url")
	out["S3_PUBLIC_URL"] = tofuOut("menu_s3_public_url")
	out["OTEL_EXPORTER_OTLP_HEADERS"] = tofuOut("menu_otel_headers")
	if menuOnHost {
		out["DATABASE_URL"] = tofuOut("menu_database_url_host")
		out["S3_ENDPOINT"] = tofuOut("menu_s3_endpoint_host")
		out["OTEL_EXPORTER_OTLP_ENDPOINT"] = tofuOut("menu_otel_endpoint_host")
	} else {
		out["DATABASE_URL"] = tofuOut("menu_database_url_container")
		out["S3_ENDPOINT"] = tofuOut("menu_s3_endpoint_container")
		out["OTEL_EXPORTER_OTLP_ENDPOINT"] = tofuOut("menu_otel_endpoint_container")
	}

	// Zitadel-apply outputs (APP_ZITADEL_* + session secret if already
	// persisted from a prior run).
	outputs, err := readOutputsJSON(outputsJSONPath)
	if err != nil {
		fail("read %s: %v", outputsJSONPath, err)
	}

	// Map outputs.json keys → menu env keys.
	pull := func(jsonKey, envKey string) {
		if v, ok := outputs[jsonKey]; ok {
			out[envKey] = v
		}
	}
	pull("APP_ZITADEL_MENU_OIDC_CLIENT_ID", "ZITADEL_OAUTH_CLIENT_ID")
	pull("APP_ZITADEL_MENU_OIDC_CLIENT_SECRET", "ZITADEL_OAUTH_CLIENT_SECRET")
	pull("APP_ZITADEL_MENU_SA_TOKEN", "ZITADEL_MANAGEMENT_TOKEN")
	pull("APP_ZITADEL_PERMISSIONS_SIGNING_KEY", "ZITADEL_ACTION_SIGNING_KEY")
	pull("APP_ZITADEL_GRANTS_SIGNING_KEY", "ZITADEL_GRANTS_SIGNING_KEY")
	pull("APP_ZITADEL_IEDORA_PROJECT_ID", "IEDORA_PROJECT_ID")

	// Session secret. Persist in outputs.json so it survives across
	// `task dev` runs (avoids invalidating local sessions every cycle).
	const sessionKey = "DEPLOY_MENU_SESSION_SECRET"
	if v, ok := outputs[sessionKey]; ok {
		out["MENU_SESSION_SECRET"] = v
	} else {
		secret, err := mintRandom32()
		if err != nil {
			fail("mint session secret: %v", err)
		}
		outputs[sessionKey] = secret
		if err := writeOutputsJSON(outputsJSONPath, outputs); err != nil {
			fail("write %s: %v", outputsJSONPath, err)
		}
		out["MENU_SESSION_SECRET"] = secret
	}

	return out
}

// readOutputsJSON loads the bin/zitadel-apply outputs file. Missing
// file → empty map (cold first run before zitadel-apply has written).
func readOutputsJSON(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]string{}, nil
		}
		return nil, err
	}
	var out map[string]string
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode: %w", err)
	}
	return out, nil
}

// writeOutputsJSON serialises in stable key order so re-runs produce
// identical files (handy for git-diff-style inspection in dev).
func writeOutputsJSON(path string, m map[string]string) error {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	ordered := make(map[string]string, len(m))
	for _, k := range keys {
		ordered[k] = m[k]
	}
	body, err := json.MarshalIndent(ordered, "", "  ")
	if err != nil {
		return err
	}
	body = append(body, '\n')
	return os.WriteFile(path, body, 0o600)
}

// mintRandom32 — 32 random bytes → URL-safe base64. Matches Stage 4's
// dockerOnHetzner.ensureAppSecrets behaviour so the prod and dev mint
// paths produce identical-shape secrets.
func mintRandom32() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// renderEnvBody serialises a map as KEY=value lines in sorted key order
// (deterministic diffs). Filters out empty values — they aren't useful
// in .env (a missing key behaves the same as KEY= for most loaders, but
// loud-omits cleaner).
func renderEnvBody(env map[string]string) string {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	for _, k := range keys {
		if env[k] == "" {
			continue
		}
		fmt.Fprintf(&b, "%s=%s\n", k, env[k])
	}
	return strings.TrimRight(b.String(), "\n")
}

// writeMenuEnvFiles is the orchestrator's post-apply hook. Composes the
// menu env in Go (no more Tofu menu_env module), then:
//
//   - Writes products/menu/.env with every key for an UP service
//     (excluded-service keys are dropped — no local listener to point at).
//   - Reconciles products/menu/.env.local: excluded-service keys appear
//     as `<please_fill>` so the operator points them at a homelab tunnel
//     / remote URL themselves. The dynamic Zitadel keys also go to
//     .env.local — they're sensitive (PAT, signing keys, secret) and
//     should NOT be committed to the repo via .env.
//
// menuOnHost is hardcoded to true in dev today: menu always runs via
// `cd products/menu && bun run dev`. A future containerized dev path
// flips this.
func writeMenuEnvFiles(devTofuDir, outputsJSONPath, envPath, envLocalPath string, selected []string) {
	env := composeMenuEnv(devTofuDir, outputsJSONPath, true)
	excluded := excludedServiceEndpoints(selected)

	// Sensitive dynamic keys go to .env.local instead of .env so they
	// don't get accidentally committed.
	dynamicKeys := []string{
		"MENU_SESSION_SECRET",
		"ZITADEL_OAUTH_CLIENT_ID",
		"ZITADEL_OAUTH_CLIENT_SECRET",
		"ZITADEL_MANAGEMENT_TOKEN",
		"ZITADEL_ACTION_SIGNING_KEY",
		"ZITADEL_GRANTS_SIGNING_KEY",
	}

	// Build the static (committed) env: full map minus dynamic keys
	// minus excluded-service keys.
	dynamicSet := map[string]bool{}
	for _, k := range dynamicKeys {
		dynamicSet[k] = true
	}
	excludedSet := map[string]bool{}
	for _, k := range excluded {
		excludedSet[k] = true
	}
	staticEnv := map[string]string{}
	for k, v := range env {
		if dynamicSet[k] || excludedSet[k] {
			continue
		}
		staticEnv[k] = v
	}
	writeEnvFile(envPath, renderEnvBody(staticEnv))

	// Build .env.local payload: dynamic Zitadel keys (always) + excluded-
	// service keys (as `<please_fill>` so operator drops in a remote URL).
	envLocalValues := map[string]string{}
	expectedKeys := []string{}
	for _, k := range dynamicKeys {
		envLocalValues[k] = env[k]
		expectedKeys = append(expectedKeys, k)
	}
	for _, k := range excluded {
		envLocalValues[k] = placeholderValue
		expectedKeys = append(expectedKeys, k)
	}
	syncEnvLocal(envLocalPath, expectedKeys, envLocalValues)
}

// ── .env.local (operator-owned, schema-synced) ───────────────────────────────

// envLine captures one KEY=value plus any preceding annotation block
// (managed lines we control, and free-form user comments we preserve).
type envLine struct {
	key      string
	value    string
	managed  string // annotationManaged | annotationStale | ""
	noteDate string // YYYY-MM-DD — preserved across runs within the same lifecycle
	userMsg  string // free-form user comment above the key (rare, but preserved)
}

// syncEnvLocal reconciles `.env.local` against the dynamic keys list.
// Behaviour per key:
//
//   - Missing                      → write the TF value, annotate `managed`
//   - Existing as `<please_fill>`  → fill with the TF value, same annotation
//   - Existing with any other value → preserve (user override; we don't touch)
//   - Stale (in file, not in schema) → keep + `# auto: stale` warn
//
// `<please_fill>` is the operator's escape hatch: setting any
// auto-managed key back to `<please_fill>` opts into the auto-fill
// on the next run.
func syncEnvLocal(path string, expectedKeys []string, dynamicValues map[string]string) {
	existing := parseEnvLocal(path)
	expectedSet := map[string]bool{}
	for _, k := range expectedKeys {
		expectedSet[k] = true
	}

	today := time.Now().UTC().Format(annotationDate)

	out := make([]envLine, 0, len(existing)+len(expectedKeys))
	addedNow := []string{}

	// Expected keys first, in caller's canonical order.
	for _, k := range expectedKeys {
		prev, ok := existing[k]
		tfVal := dynamicValues[k]
		switch {
		case !ok:
			out = append(out, envLine{
				key: k, value: tfVal,
				managed:  annotationManaged,
				noteDate: today,
			})
			addedNow = append(addedNow, k)
		case prev.value == placeholderValue:
			// Refill from the TF value. Keep the date the placeholder
			// was first written if we can (don't reset on every refill).
			d := prev.noteDate
			if d == "" {
				d = today
			}
			out = append(out, envLine{
				key: k, value: tfVal,
				managed: annotationManaged, noteDate: d,
				userMsg: prev.userMsg,
			})
		default:
			// User-set value (override OR previously auto-filled value
			// the user is happy with). Preserve verbatim; strip the
			// `managed` annotation.
			out = append(out, envLine{
				key: k, value: prev.value,
				userMsg: prev.userMsg,
			})
		}
	}

	// Stale keys (in file but not in schema) — at the end, with the
	// annotation date preserved across runs.
	for k, prev := range existing {
		if expectedSet[k] {
			continue
		}
		d := prev.noteDate
		if d == "" || prev.managed != annotationStale {
			d = today
		}
		out = append(out, envLine{
			key: k, value: prev.value,
			managed: annotationStale, noteDate: d,
			userMsg: prev.userMsg,
		})
		warn(".env.local key %q is stale (not in schema since %s) — safe to remove.", k, d)
	}

	if err := os.WriteFile(path, []byte(renderEnvLocal(out)), envLocalFileMode); err != nil {
		fail("write %s: %v", path, err)
	}
	if len(addedNow) > 0 {
		fmt.Printf("%s .env.local: filled %d key(s) from TF — %s\n",
			logPrefix, len(addedNow), strings.Join(addedNow, ", "))
	}
}

// parseEnvLocal reads a previous `.env.local` emit (or a hand-edited
// file). Recognises:
//   - managed annotations `# auto: <kind> — …: YYYY-MM-DD`
//   - free-form user comments above a KEY= line
//   - KEY=VALUE
func parseEnvLocal(path string) map[string]envLine {
	out := map[string]envLine{}
	raw, err := os.ReadFile(path)
	if err != nil {
		return out
	}
	var pendingKind, pendingDate, pendingUserMsg string
	for _, line := range strings.Split(string(raw), "\n") {
		trimmed := strings.TrimRight(line, "\r")
		if strings.HasPrefix(trimmed, managedNotePrefix) {
			pendingKind, pendingDate = parseManagedAnnotation(trimmed)
			continue
		}
		if strings.HasPrefix(trimmed, "#") {
			if pendingUserMsg == "" {
				pendingUserMsg = trimmed
			} else {
				pendingUserMsg += "\n" + trimmed
			}
			continue
		}
		if trimmed == "" {
			pendingUserMsg = ""
			continue
		}
		eq := strings.IndexByte(trimmed, '=')
		if eq <= 0 {
			continue
		}
		k := trimmed[:eq]
		out[k] = envLine{
			key:      k,
			value:    trimmed[eq+1:],
			managed:  pendingKind,
			noteDate: pendingDate,
			userMsg:  pendingUserMsg,
		}
		pendingKind = ""
		pendingDate = ""
		pendingUserMsg = ""
	}
	return out
}

// parseManagedAnnotation decodes one `# auto: <kind> — …: <date>` line.
// Legacy "added" → normalised to annotationManaged (transparent
// migration of pre-Option-2 files).
func parseManagedAnnotation(line string) (kind, date string) {
	body := strings.TrimPrefix(line, managedNotePrefix)
	switch {
	case strings.HasPrefix(body, annotationManaged):
		kind = annotationManaged
	case strings.HasPrefix(body, annotationAdded):
		kind = annotationManaged
	case strings.HasPrefix(body, annotationStale):
		kind = annotationStale
	}
	if i := strings.LastIndex(body, ": "); i >= 0 {
		date = strings.TrimSpace(body[i+2:])
	}
	return
}

// renderEnvLocal serialises the reconciled lines back to file content.
func renderEnvLocal(lines []envLine) string {
	var b strings.Builder
	b.WriteString("# USER-owned. `just dev` reconciles this file with the TF schema:\n")
	b.WriteString("#   - missing keys are filled with the current TF value\n")
	b.WriteString("#   - keys set to `<please_fill>` are refilled with the TF value\n")
	b.WriteString("#   - keys with any other value are left alone (your overrides)\n")
	b.WriteString("#   - stale keys (no longer in schema) flagged with `# auto: stale`\n")
	b.WriteString("# To force a refill: set the value back to `<please_fill>` and re-run.\n")
	b.WriteString("\n")
	for _, l := range lines {
		if l.userMsg != "" {
			b.WriteString(l.userMsg)
			b.WriteByte('\n')
		}
		switch l.managed {
		case annotationManaged:
			fmt.Fprintf(&b, "%s%s — TF-owned (auto-filled %s; edit to override)\n",
				managedNotePrefix, annotationManaged, l.noteDate)
		case annotationStale:
			fmt.Fprintf(&b, "%s%s — not in menu_env schema since %s, safe to remove\n",
				managedNotePrefix, annotationStale, l.noteDate)
		}
		fmt.Fprintf(&b, "%s=%s\n", l.key, l.value)
		b.WriteByte('\n')
	}
	return b.String()
}

// ── Override warnings (pre-apply visibility) ─────────────────────────────────

// warnEnvLocalState surveys `.env.local` BEFORE the apply runs and
// prints one or both notices, depending on what it finds:
//
//  1. An override for a key whose service IS running locally — the menu
//     will route to the override and silently bypass the local listener.
//     Often unintentional (stale value from a previous --except run).
//
//  2. An override for an --except'd service — expected, but the operator
//     should see the value about to be used (no surprises).
//
// Both cases share the same signal: a `.env.local` entry with a
// non-placeholder, non-empty value. The selection (which keys are
// "excluded") determines whether each is foot-gun or expected.
func warnEnvLocalState(envLocalPath string, selected []string) {
	existing := parseEnvLocal(envLocalPath)
	if len(existing) == 0 {
		return
	}
	excludedSet := map[string]bool{}
	for _, k := range excludedServiceEndpoints(selected) {
		excludedSet[k] = true
	}
	var shadowing, expected []string
	for k, line := range existing {
		// Only KEY=<real value> counts as an override. KEY= (empty)
		// or KEY=<please_fill> is the orchestrator's own scaffolding.
		// TrimSpace catches trailing whitespace edge cases.
		v := strings.TrimSpace(line.value)
		if v == "" || v == placeholderValue {
			continue
		}
		if excludedSet[k] {
			expected = append(expected, k)
		} else {
			shadowing = append(shadowing, k)
		}
	}
	sort.Strings(shadowing)
	sort.Strings(expected)

	if len(shadowing) > 0 {
		warn(".env.local overrides keys whose service IS running locally — the menu will use the override, NOT the local service:")
		for _, k := range shadowing {
			fmt.Fprintf(os.Stderr, "         %s = %s\n", k, redact(existing[k].value))
		}
		fmt.Fprintln(os.Stderr, "       to use the local service: reset the value to `<please_fill>` (auto-refills) or delete the line.")
	}
	if len(expected) > 0 {
		info(".env.local overrides for --except'd services (menu will use these):")
		for _, k := range expected {
			fmt.Fprintf(os.Stderr, "         %s = %s\n", k, redact(existing[k].value))
		}
	}
}

// redact shortens a value for terminal display — values over
// redactThreshold print as their first 12 chars + an ellipsis with the
// full length. Short values pass through verbatim. Keeps full PATs and
// session secrets from spraying across the operator's scrollback.
func redact(v string) string {
	if len(v) <= redactThreshold {
		return v
	}
	return fmt.Sprintf("%s…(%d chars)", v[:12], len(v))
}
