package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// ── .env writer (committed, TF-owned) ────────────────────────────────────────

func writeEnvFile(path, body string) {
	if body == "" {
		return
	}
	header := "# AUTO-GENERATED by `just dev` (infra/modules/menu_env + dev.go).\n" +
		"# Full local env: every key has a real value (the random ones are\n" +
		"# regenerated by Tofu on a fresh `just dev-down` + `just dev`).\n" +
		"# These are local-only values — no prod leak. Commit when the\n" +
		"# schema evolves; the random values are also safe to commit (they\n" +
		"# only unlock the operator's own localhost stack).\n" +
		"# Overrides live in `.env.local` (gitignored, user-owned).\n\n"
	if err := os.WriteFile(path, []byte(header+body+"\n"), envFileMode); err != nil {
		fail("write %s: %v", path, err)
	}
}

// mergeEnvFiles overlays the `env_dynamic_file` values on top of
// `env_committable_file`. The static body has placeholders
// (`<please_fill>`) for the dynamic keys; the dynamic body has the
// real Tofu-generated values. The merged result has every key filled.
func mergeEnvFiles(static, dynamic string) string {
	overrides := parseEnvBody(dynamic)
	var out strings.Builder
	lines := strings.Split(static, "\n")
	for i, line := range lines {
		eq := strings.IndexByte(line, '=')
		if eq <= 0 {
			out.WriteString(line)
		} else if v, ok := overrides[line[:eq]]; ok {
			out.WriteString(line[:eq])
			out.WriteByte('=')
			out.WriteString(v)
		} else {
			out.WriteString(line)
		}
		if i < len(lines)-1 {
			out.WriteByte('\n')
		}
	}
	return out.String()
}

// dropEnvKeys removes any KEY=value line whose KEY is in the drop set.
// Used to keep `.env` honest: when a service was excluded from the dev
// stack, the env keys that point at it shouldn't appear in `.env` —
// they'd be lies (e.g., OTEL_*=http://localhost:5080/... with nothing
// listening). Those keys move to `.env.local` as `<please_fill>`.
func dropEnvKeys(body string, dropKeys []string) string {
	if len(dropKeys) == 0 {
		return body
	}
	drop := map[string]bool{}
	for _, k := range dropKeys {
		drop[k] = true
	}
	var out strings.Builder
	lines := strings.Split(body, "\n")
	first := true
	for _, line := range lines {
		eq := strings.IndexByte(line, '=')
		if eq > 0 && drop[line[:eq]] {
			continue
		}
		if !first {
			out.WriteByte('\n')
		}
		out.WriteString(line)
		first = false
	}
	return out.String()
}

// parseEnvBody turns a multi-line `KEY=value` body (e.g. the output of
// `tofu output -raw env_dynamic_file`) into a map. Tolerant of blank
// lines and comments — anything without `=` is skipped.
func parseEnvBody(body string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(body, "\n") {
		eq := strings.IndexByte(line, '=')
		if eq <= 0 {
			continue
		}
		out[line[:eq]] = line[eq+1:]
	}
	return out
}

// ── .env.local (operator-owned, schema-synced) ───────────────────────────────

// envLine captures one KEY=value plus any preceding annotation block
// (managed lines we control, and free-form user comments we preserve).
type envLine struct {
	key      string
	value    string
	managed  string // annotationManaged | annotationStale | ""
	noteDate string // YYYY-MM-DD — preserved across runs within the same lifecycle
	userMsg  string // free-form user comment above the key (rare, but preserved)
}

// syncEnvLocal reconciles `.env.local` against the dynamic keys list.
// Behaviour per key:
//
//   - Missing                      → write the TF value, annotate `managed`
//   - Existing as `<please_fill>`  → fill with the TF value, same annotation
//   - Existing with any other value → preserve (user override; we don't touch)
//   - Stale (in file, not in schema) → keep + `# auto: stale` warn
//
// `<please_fill>` is the operator's escape hatch: setting any
// auto-managed key back to `<please_fill>` opts into the auto-fill
// on the next run.
func syncEnvLocal(path string, expectedKeys []string, dynamicValues map[string]string) {
	existing := parseEnvLocal(path)
	expectedSet := map[string]bool{}
	for _, k := range expectedKeys {
		expectedSet[k] = true
	}

	today := time.Now().UTC().Format(annotationDate)

	out := make([]envLine, 0, len(existing)+len(expectedKeys))
	addedNow := []string{}

	// Expected keys first, in caller's canonical order.
	for _, k := range expectedKeys {
		prev, ok := existing[k]
		tfVal := dynamicValues[k]
		switch {
		case !ok:
			out = append(out, envLine{
				key: k, value: tfVal,
				managed:  annotationManaged,
				noteDate: today,
			})
			addedNow = append(addedNow, k)
		case prev.value == placeholderValue:
			// Refill from the TF value. Keep the date the placeholder
			// was first written if we can (don't reset on every refill).
			d := prev.noteDate
			if d == "" {
				d = today
			}
			out = append(out, envLine{
				key: k, value: tfVal,
				managed: annotationManaged, noteDate: d,
				userMsg: prev.userMsg,
			})
		default:
			// User-set value (override OR previously auto-filled value
			// the user is happy with). Preserve verbatim; strip the
			// `managed` annotation.
			out = append(out, envLine{
				key: k, value: prev.value,
				userMsg: prev.userMsg,
			})
		}
	}

	// Stale keys (in file but not in schema) — at the end, with the
	// annotation date preserved across runs.
	for k, prev := range existing {
		if expectedSet[k] {
			continue
		}
		d := prev.noteDate
		if d == "" || prev.managed != annotationStale {
			d = today
		}
		out = append(out, envLine{
			key: k, value: prev.value,
			managed: annotationStale, noteDate: d,
			userMsg: prev.userMsg,
		})
		warn(".env.local key %q is stale (not in schema since %s) — safe to remove.", k, d)
	}

	if err := os.WriteFile(path, []byte(renderEnvLocal(out)), envLocalFileMode); err != nil {
		fail("write %s: %v", path, err)
	}
	if len(addedNow) > 0 {
		fmt.Printf("%s .env.local: filled %d key(s) from TF — %s\n",
			logPrefix, len(addedNow), strings.Join(addedNow, ", "))
	}
}

// parseEnvLocal reads a previous `.env.local` emit (or a hand-edited
// file). Recognises:
//   - managed annotations `# auto: <kind> — …: YYYY-MM-DD`
//   - free-form user comments above a KEY= line
//   - KEY=VALUE
func parseEnvLocal(path string) map[string]envLine {
	out := map[string]envLine{}
	raw, err := os.ReadFile(path)
	if err != nil {
		return out
	}
	var pendingKind, pendingDate, pendingUserMsg string
	for _, line := range strings.Split(string(raw), "\n") {
		trimmed := strings.TrimRight(line, "\r")
		if strings.HasPrefix(trimmed, managedNotePrefix) {
			pendingKind, pendingDate = parseManagedAnnotation(trimmed)
			continue
		}
		if strings.HasPrefix(trimmed, "#") {
			if pendingUserMsg == "" {
				pendingUserMsg = trimmed
			} else {
				pendingUserMsg += "\n" + trimmed
			}
			continue
		}
		if trimmed == "" {
			pendingUserMsg = ""
			continue
		}
		eq := strings.IndexByte(trimmed, '=')
		if eq <= 0 {
			continue
		}
		k := trimmed[:eq]
		out[k] = envLine{
			key:      k,
			value:    trimmed[eq+1:],
			managed:  pendingKind,
			noteDate: pendingDate,
			userMsg:  pendingUserMsg,
		}
		pendingKind = ""
		pendingDate = ""
		pendingUserMsg = ""
	}
	return out
}

// parseManagedAnnotation decodes one `# auto: <kind> — …: <date>` line.
// Legacy "added" → normalised to annotationManaged (transparent
// migration of pre-Option-2 files).
func parseManagedAnnotation(line string) (kind, date string) {
	body := strings.TrimPrefix(line, managedNotePrefix)
	switch {
	case strings.HasPrefix(body, annotationManaged):
		kind = annotationManaged
	case strings.HasPrefix(body, annotationAdded):
		kind = annotationManaged
	case strings.HasPrefix(body, annotationStale):
		kind = annotationStale
	}
	if i := strings.LastIndex(body, ": "); i >= 0 {
		date = strings.TrimSpace(body[i+2:])
	}
	return
}

// renderEnvLocal serialises the reconciled lines back to file content.
func renderEnvLocal(lines []envLine) string {
	var b strings.Builder
	b.WriteString("# USER-owned. `just dev` reconciles this file with the TF schema:\n")
	b.WriteString("#   - missing keys are filled with the current TF value\n")
	b.WriteString("#   - keys set to `<please_fill>` are refilled with the TF value\n")
	b.WriteString("#   - keys with any other value are left alone (your overrides)\n")
	b.WriteString("#   - stale keys (no longer in schema) flagged with `# auto: stale`\n")
	b.WriteString("# To force a refill: set the value back to `<please_fill>` and re-run.\n")
	b.WriteString("\n")
	for _, l := range lines {
		if l.userMsg != "" {
			b.WriteString(l.userMsg)
			b.WriteByte('\n')
		}
		switch l.managed {
		case annotationManaged:
			fmt.Fprintf(&b, "%s%s — TF-owned (auto-filled %s; edit to override)\n",
				managedNotePrefix, annotationManaged, l.noteDate)
		case annotationStale:
			fmt.Fprintf(&b, "%s%s — not in menu_env schema since %s, safe to remove\n",
				managedNotePrefix, annotationStale, l.noteDate)
		}
		fmt.Fprintf(&b, "%s=%s\n", l.key, l.value)
		b.WriteByte('\n')
	}
	return b.String()
}

// ── Override warnings (pre-apply visibility) ─────────────────────────────────

// warnEnvLocalState surveys `.env.local` BEFORE the apply runs and
// prints one or both notices, depending on what it finds:
//
//  1. An override for a key whose service IS running locally — the menu
//     will route to the override and silently bypass the local listener.
//     Often unintentional (stale value from a previous --except run).
//
//  2. An override for an --except'd service — expected, but the operator
//     should see the value about to be used (no surprises).
//
// Both cases share the same signal: a `.env.local` entry with a
// non-placeholder, non-empty value. The selection (which keys are
// "excluded") determines whether each is foot-gun or expected.
func warnEnvLocalState(envLocalPath string, selected []string) {
	existing := parseEnvLocal(envLocalPath)
	if len(existing) == 0 {
		return
	}
	excludedSet := map[string]bool{}
	for _, k := range excludedServiceEndpoints(selected) {
		excludedSet[k] = true
	}
	var shadowing, expected []string
	for k, line := range existing {
		// Only KEY=<real value> counts as an override. KEY= (empty)
		// or KEY=<please_fill> is the orchestrator's own scaffolding.
		// TrimSpace catches trailing whitespace edge cases.
		v := strings.TrimSpace(line.value)
		if v == "" || v == placeholderValue {
			continue
		}
		if excludedSet[k] {
			expected = append(expected, k)
		} else {
			shadowing = append(shadowing, k)
		}
	}
	sort.Strings(shadowing)
	sort.Strings(expected)

	if len(shadowing) > 0 {
		warn(".env.local overrides keys whose service IS running locally — the menu will use the override, NOT the local service:")
		for _, k := range shadowing {
			fmt.Fprintf(os.Stderr, "         %s = %s\n", k, redact(existing[k].value))
		}
		fmt.Fprintln(os.Stderr, "       to use the local service: reset the value to `<please_fill>` (auto-refills) or delete the line.")
	}
	if len(expected) > 0 {
		info(".env.local overrides for --except'd services (menu will use these):")
		for _, k := range expected {
			fmt.Fprintf(os.Stderr, "         %s = %s\n", k, redact(existing[k].value))
		}
	}
}

// redact shortens a value for terminal display — values over
// redactThreshold print as their first 12 chars + an ellipsis with the
// full length. Short values pass through verbatim. Keeps full PATs and
// session secrets from spraying across the operator's scrollback.
func redact(v string) string {
	if len(v) <= redactThreshold {
		return v
	}
	return fmt.Sprintf("%s…(%d chars)", v[:12], len(v))
}
