import { betterAuth } from 'better-auth'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'
import { admin } from 'better-auth/plugins/admin'
import { jwt } from 'better-auth/plugins/jwt'
import { organization } from 'better-auth/plugins/organization'
import { oauthProvider } from '@better-auth/oauth-provider'
import type { PgDatabase, PgQueryResultHKT } from 'drizzle-orm/pg-core'
import { eq } from 'drizzle-orm'
import { db } from '@/shared/db/client'
import * as schema from '@/shared/db/schema'
import { env } from '@/shared/env'
import { emit } from '@/features/webhooks'

type AuthDb = PgDatabase<PgQueryResultHKT, typeof schema>

/**
 * Every model Better Auth touches at runtime, given Genkan's plugin set.
 * Exported so tests can assert completeness against a known-good list — if
 * you enable a Better Auth plugin or storage option that adds a new model,
 * register it here AND mirror it on `BA_MODELS` so the integration test
 * catches the wiring gap before it ships.
 */
export const BA_MODELS = {
  user: schema.user,
  session: schema.session,
  account: schema.account,
  verification: schema.verification,
  organization: schema.organization,
  member: schema.member,
  invitation: schema.invitation,
  rateLimit: schema.rateLimit,
  // jwt plugin — JWKS for signing OIDC tokens.
  jwks: schema.jwks,
  // oauth-provider plugin tables. Generated by `bun run auth:generate`.
  oauthClient: schema.oauthClient,
  oauthAccessToken: schema.oauthAccessToken,
  oauthRefreshToken: schema.oauthRefreshToken,
  oauthConsent: schema.oauthConsent,
} as const

/**
 * Pre-registered first-party clients. Each tuple in TRUSTED_CLIENTS is
 *
 *   client_id|client_secret|redirect_uri_1,redirect_uri_2
 *
 * with one tuple per line / comma-separated outer pieces. We mark every
 * entry `skipConsent=true` so signed-in users coming from menu (or future
 * first-party products) don't see the consent screen — by definition the
 * iedora estate has already consented to its own apps.
 */
function parseTrustedClients(raw: string | undefined) {
  if (!raw) return [] as const
  return raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [clientId, clientSecret, redirectUris] = line.split('|')
      if (!clientId || !clientSecret || !redirectUris) {
        throw new Error(
          `Invalid TRUSTED_CLIENTS entry — expected "id|secret|uri1,uri2", got: ${line}`,
        )
      }
      return {
        client_id: clientId,
        client_secret: clientSecret,
        redirect_uris: redirectUris.split(',').map((u) => u.trim()),
        // Auto-grant scopes — first-party only.
        skipConsent: true,
        // Full OIDC + the iedora product scopes.
        scope: 'openid profile email offline_access menu org:read org:admin',
      } as const
    })
}

const TRUSTED_CLIENTS = parseTrustedClients(env.TRUSTED_CLIENTS)

/**
 * In-flight state captured in the `before` hook so the corresponding
 * `after` hook can compute transitions (e.g. banned → unbanned) without
 * relying on the partial-update payload. Keyed by user id; admin updates
 * on the same user serialize through `auth.api.*` so the window is short.
 *
 * If a concurrent update happens to evict the entry before `after` runs
 * we just skip the transition event — that's a fail-soft outcome, never
 * a duplicate emit.
 */
type PriorUserState = {
  banned: boolean
  role: string | null
}

/**
 * Factory. Production uses the singleton at the bottom; tests construct
 * their own instance pointed at a PGLite db to exercise the real adapter
 * wiring (e.g. catch "model X not found in schema object" before deploy).
 */
export function makeAuth(database: AuthDb) {
  const priorUserState = new Map<string, PriorUserState>()

  async function snapshotUser(userId: string): Promise<void> {
    const [row] = await database
      .select({
        banned: schema.user.banned,
        role: schema.user.role,
      })
      .from(schema.user)
      .where(eq(schema.user.id, userId))
      .limit(1)
    if (row) {
      priorUserState.set(userId, {
        banned: Boolean(row.banned),
        role: row.role ?? null,
      })
    }
  }

  return betterAuth({
    baseURL: env.BETTER_AUTH_URL,
    database: drizzleAdapter(database, {
      provider: 'pg',
      schema: BA_MODELS,
    }),
    trustedOrigins: env.TRUSTED_ORIGINS,
    // Pin log level in prod — Better Auth's default `info` prints token
    // request/response payloads, which is too chatty for an IdP and a
    // PII/credential leak risk in shared log sinks. Verbose locally.
    logger: {
      level: process.env.NODE_ENV === 'production' ? 'error' : 'info',
      disabled: false,
    },
    emailAndPassword: {
      enabled: true,
      // Better Auth's default is 8. NIST SP 800-63B says ≥8 with no special
      // characters, but a 12-char minimum is the modern baseline (1Password,
      // Auth0, Clerk all default ≥10–12) and pinning it makes the policy
      // diff-visible at review.
      minPasswordLength: 12,
    },
    // Better Auth 1.6.x ships an opt-out telemetry collector that reports
    // anonymous version + feature usage. Explicit opt-out for an IdP — we
    // don't want any third-party observation of our identity surface, and
    // an explicit value is resilient to a future default flip.
    telemetry: { enabled: false },
    rateLimit: {
      enabled: process.env.DISABLE_AUTH_RATE_LIMIT !== 'true',
      storage: 'database',
    },
    // Platform-admin field on the user. Users default to "user"; flipping a
    // row to "admin" gates access to /admin. The admin plugin reads this.
    user: {
      additionalFields: {
        role: {
          type: 'string',
          required: false,
          defaultValue: 'user',
          input: false, // not settable through public signup
        },
      },
    },
    // Step-up freshness marker. `lastPasswordAt` is the timestamp of the
    // most recent password confirmation on this session row. Initialized
    // at session creation (see `databaseHooks.session.create.before` below)
    // and refreshed by the /reauth flow. Read by `requireFreshSession()` to
    // gate destructive operations (user/org/app delete, role-to-admin,
    // impersonate, ban, etc).
    session: {
      additionalFields: {
        lastPasswordAt: {
          type: 'date',
          required: false,
          input: false,
        },
      },
    },
    advanced: {
      // No more crossSubDomainCookies — products federate via OIDC now. Each
      // app keeps its own host-scoped cookie; the OAuth handshake carries
      // identity between hosts.
      ipAddress: {
        ipAddressHeaders: ['cf-connecting-ip'],
        ipv6Subnet: 64,
      },
      // Force Secure + `__Secure-` prefix in every environment. Better Auth's
      // auto-detection (baseURL starts with https://) already lands on this
      // in prod, but the explicit flag is diff-visible at review and
      // resilient to a future config change that flips baseURL to a Proxy /
      // dynamic descriptor. Cloudflared terminates TLS at the edge and
      // forwards HTTP to origin — without this, BA could decide cookies are
      // non-secure on the basis of the origin scheme.
      useSecureCookies: true,
      // TODO(hardening): promote cookie prefix to `__Host-` once we've
      // verified neither BA itself nor any first-party client sets the
      // Domain attribute. Today we don't (crossSubDomainCookies is off) so
      // the switch is technically safe, but the option would require us to
      // override `advanced.cookies.session_token.name` explicitly per cookie
      // and Better Auth's helpers like `getSessionCookie` already strip
      // `__Secure-` / `__Host-` transparently. Defer until we run a full
      // session-survival check on a staging deploy.
    },
    /**
     * Better Auth lifecycle hooks → @iedora/identity webhook emits.
     *
     * Only the user model has core hooks (Better Auth 1.6.11). For
     * organizations + members we plug into the organization plugin's
     * own `*Organization` / `*Member` callbacks below.
     */
    databaseHooks: {
      // Stamp every new session with a fresh `lastPasswordAt`. This covers
      // sign-in (email+password), sign-up (auto-session), and impersonation
      // (a new session row is created for the actor). Without this hook the
      // `defaultNow()` Drizzle default still fires, but the explicit assign
      // is diff-visible and survives a future schema-side change to the
      // column default.
      session: {
        create: {
          before: async (sessionRow) => {
            // Only assign when missing — preserve any value the caller set
            // explicitly (e.g. the /reauth path UPDATEs by id, so create
            // hooks shouldn't run there, but stay defensive).
            if (!('lastPasswordAt' in sessionRow) || sessionRow.lastPasswordAt == null) {
              return {
                data: { ...sessionRow, lastPasswordAt: new Date() },
              }
            }
            return undefined
          },
        },
      },
      user: {
        update: {
          before: async (user) => {
            if (typeof user.id === 'string') {
              await snapshotUser(user.id)
            }
          },
          after: async (user) => {
            const prior = priorUserState.get(user.id)
            priorUserState.delete(user.id)
            const banned = Boolean(user.banned)
            const role = typeof user.role === 'string' ? user.role : null

            if (prior) {
              if (!prior.banned && banned) {
                await emit({
                  event: 'user.banned',
                  payload: {
                    user_id: user.id,
                    reason:
                      typeof user.banReason === 'string'
                        ? user.banReason
                        : undefined,
                    expires:
                      user.banExpires instanceof Date
                        ? user.banExpires.toISOString()
                        : user.banExpires == null
                          ? null
                          : String(user.banExpires),
                  },
                })
              } else if (prior.banned && !banned) {
                await emit({
                  event: 'user.unbanned',
                  payload: { user_id: user.id },
                })
              }
              if (role && prior.role !== role) {
                await emit({
                  event: 'user.role_changed',
                  payload: { user_id: user.id, role },
                })
              }
            }
          },
        },
        delete: {
          after: async (user) => {
            await emit({
              event: 'user.deleted',
              payload: { user_id: user.id },
            })
          },
        },
      },
    },
    plugins: [
      // Better Auth 1.6.11 flipped the verification default; we don't ship
      // email verification yet so leaving the flag at the new default would
      // silently reject every invite. Flip when the email-sender lands.
      organization({
        requireEmailVerificationOnInvitation: false,
        organizationHooks: {
          afterCreateOrganization: async ({ organization: org }) => {
            await emit({
              event: 'org.created',
              payload: {
                org_id: org.id,
                slug: org.slug,
                name: org.name,
              },
            })
          },
          afterUpdateOrganization: async ({ organization: org }) => {
            if (!org) return
            await emit({
              event: 'org.updated',
              payload: {
                org_id: org.id,
                slug: org.slug,
                name: org.name,
              },
            })
          },
          afterDeleteOrganization: async ({ organization: org }) => {
            await emit({
              event: 'org.deleted',
              payload: { org_id: org.id },
            })
          },
          afterAddMember: async ({ member }) => {
            await emit({
              event: 'org.member_added',
              payload: {
                org_id: member.organizationId,
                user_id: member.userId,
                role: member.role,
              },
            })
          },
          afterRemoveMember: async ({ member }) => {
            await emit({
              event: 'org.member_removed',
              payload: {
                org_id: member.organizationId,
                user_id: member.userId,
              },
            })
          },
          afterUpdateMemberRole: async ({ member }) => {
            await emit({
              event: 'org.member_role_changed',
              payload: {
                org_id: member.organizationId,
                user_id: member.userId,
                role: member.role,
              },
            })
          },
        },
      }),

      // Platform-admin APIs: list/create/disable users, list sessions, etc.
      // Routes are gated server-side by user.role==='admin'.
      admin(),

      // JWT signing for OAuth tokens. The oauth-provider plugin requires
      // this — id_tokens and access_tokens are signed RS256 with a key
      // material managed by the JWT plugin. Exposes /.well-known/jwks.json
      // so any OIDC client (.NET, Go, Node, etc.) verifies tokens via JWKS.
      jwt(),

      // OAuth 2.1 + OIDC provider. Genkan becomes the canonical IdP for the
      // iedora estate. Menu and future products (incl. .NET APIs) federate
      // here. Standard `.well-known/openid-configuration` + JWKS so any
      // OIDC-compliant client validates tokens without bespoke code.
      oauthProvider({
        loginPage: '/login',
        consentPage: '/consent',
        // Dynamic client registration MUST stay off — first-party clients
        // are seeded by scripts/migrate.mjs from TRUSTED_CLIENTS and any
        // third-party client is created via the admin UI calling
        // `auth.api.registerOAuthClient` (server-side). Better Auth defaults
        // both flags to `false`; pinning here makes the security posture
        // explicit and resistant to a future default flip. The `/oauth2/
        // register` endpoint returns FORBIDDEN with either flag off.
        allowDynamicClientRegistration: false,
        allowUnauthenticatedClientRegistration: false,
        // Supported scopes. `openid profile email offline_access` are the
        // OIDC standards; the rest are iedora-specific product/role grants.
        scopes: [
          'openid',
          'profile',
          'email',
          'offline_access',
          'menu', // access to the menu product
          'org:read', // can read user's organizations + members
          'org:admin', // can create/update/delete organizations
        ],
        // Set of client_ids to mark as pre-trusted: their oauth_client rows
        // are cached + made immutable through the public CRUD endpoints.
        // The actual rows are seeded into the DB by scripts/migrate.mjs
        // from the TRUSTED_CLIENTS env var; this set is just the pin list.
        cachedTrustedClients: new Set(
          TRUSTED_CLIENTS.map((c) => c.client_id),
        ),
        // Sign-up landing within the OIDC `prompt=create` flow.
        signup: {
          page: '/signup',
        },
        // Genkan claims to expose in the userinfo response — organizations
        // + role go here so OAuth clients (menu, .NET APIs) read identity
        // membership from the JWT, not from a sibling DB.
        getAdditionalUserInfoClaim: async (
          user: { id: string; role?: string },
          scopes: string[],
        ) => {
          const claims: Record<string, unknown> = {}
          // `org:read` = include orgs the user is a member of.
          if (scopes.includes('org:read')) {
            // Lazy-load to avoid a static cycle through plugins/auth.
            const { listUserOrganizations } = await import(
              '@/features/auth/use-cases/list-user-organizations'
            )
            claims.organizations = await listUserOrganizations(user.id)
          }
          // Always include platform role — needed by genkan's own /admin gate.
          const u = user as typeof user & { role?: string }
          if (u.role) claims.role = u.role
          return claims
        },
      }),
    ],
  })
}

export const auth = makeAuth(db)

export type Session = typeof auth.$Infer.Session
